### ISSUE TITLE
Some questions about EDRM's input

### ISSUE THREAD

**Issue by JShanPP** [thunlp/EntityDuetNeuralRanking#12]
Hi , I have some questions about EDRM's input. I've download CN-DBpedia and found it contains data of triples. How can I get entity description and entity type? And in  the "EDRM/preprocess.py" , what is the "-ent_car" ?  What kind of data format do I need ? 
Looking forward to your reply and thanks!

**Comment by EdwardZH** [comment]
Thank you for your attention. For a triple (head entity, relation, tail entity), the relation ''BaiduCARD'' means description and ''BaiduTAG'' means entity types. ''-ent_car'' means entity type (category). I will upload the processed data later. And we now are working for the English version.

**Comment by EdwardZH** [comment]
Hello, I have uploaded all data. And you can follow our instructions. I will close this issue. Thank you for your attention.
