### ISSUE TITLE
when run train.py, it pops up "No such file or directory: 'TRAIN' ".

### ISSUE THREAD

**Issue by bayou3** [thunlp/EntityDuetNeuralRanking#13]
Hi, I have downloaded all files provided by "https://cloud.tsinghua.edu.cn/d/1f57be663018465ab0ad/?p=%2F&mode=list". Then I run "python2 train.py -data ~/data/ednr/data.pt -train TRAIN -valid VALID -test_data ~/data/ednr/test.pt  -save_model ~/data/ednr/save -save_mode best".  But it pops up an error of "IOError: [Errno 2] No such file or directory: 'TRAIN'".  All the files from the data website are "data.pt, tag_result, test.pt, title.emb". Is data.pt is the file of train.py? I copied data.pt to a file named "TRAIN", it also went wrong.

**Comment by EdwardZH** [comment]
Hello, I will update our code soon. Thank you for your bug report.

**Comment by EdwardZH** [comment]
Hi, I have update running data and provide scripts to run our models. For EDRM version, you can refer to our OpenMatch tookit,https://github.com/thunlp/OpenMatch. The EDRM will release soon.
