### ISSUE TITLE
test_diff.qrel; test_same.qrel文件没有提供

### ISSUE THREAD

**Issue by gaoliming123** [thunlp/EntityDuetNeuralRanking#16]
您好，您的在datahttps://github.com/thunlp/EntityDuetNeuralRanking/tree/master/data中说所有的文件都可以在此链接https://cloud.tsinghua.edu.cn/d/1f57be663018465ab0ad/?p=%2F&mode=list中下载，但是这个链接中并没有提供test_diff.qrel; test_same.qrel这两个文件。
您链接中提供的所有数据如下：
![image](https://user-images.githubusercontent.com/19948248/105868744-748d1880-6031-11eb-8474-1ff12447b286.png)

**Comment by EdwardZH** [comment]
These files can be found in the evaluation fold and you can find all evaluation processes.

**Comment by gaoliming123** [comment]
谢谢
