### ISSUE TITLE
Hello, where can I get the content of the corresponding "sogou-id"?

### ISSUE THREAD

**Issue by OleNet** [thunlp/EntityDuetNeuralRanking#18]
Hi ,  as the picture shows that I have printed the content of the file of "test_raw.json"  hosted in the [pan of tsinghua](https://cloud.tsinghua.edu.cn/d/1bfff521fd784b95ac45/?p=%2Fjson&mode=list), 

![dc3d9b108a2b78054cbd99f0fe98b03a](https://user-images.githubusercontent.com/3206718/124140169-d5c28780-daba-11eb-8a98-f62d404ceda5.png)

However, it seems that a lot of content corresponding to the "sogou-id" can't be found from any of those files stored in https://cloud.tsinghua.edu.cn/d/1bfff521fd784b95ac45/?p=%2Fjson&mode=list 

So I want to ask where can I find the content corresponding to the "sougou-id", e.g. "sogou-14837"? 

Thanks in advance.

**Comment by EdwardZH** [comment]
We do not provide the raw data. You can follow our code https://github.com/thunlp/EntityDuetNeuralRanking/blob/97525c7d136108bbdf69fc094c322c3b8300002e/EDRM/train.py#L42 to extract the data from test.py.

**Comment by OleNet** [comment]
Because it is said that the MRR is calculated from Testing-Raw according to your paper , and NDCG is calculated from Testing-SAME and Testing-DIFF ![image](https://user-images.githubusercontent.com/3206718/124146738-a44cba80-dac0-11eb-9a55-b9d4815b1d13.png)

if I can't get the raw data of test-raw.json, how can I predict test.raw and calculate MRR like the data from your paper ? 
![image](https://user-images.githubusercontent.com/3206718/124146616-8717ec00-dac0-11eb-82ca-5f6f9926b9a6.png)

Is there anything I got wrong or misunderstood, please point me out, 

Thanks a lot.

**Comment by EdwardZH** [comment]
For evaluation, please refer to our evaluation instuction https://github.com/thunlp/EntityDuetNeuralRanking/tree/master/evaluation. During the evaluation, we do not need the query text.

**Comment by OleNet** [comment]
OK, I got it. 
Thanks for your reply.
