### ISSUE TITLE
Which part of the EDRM code introduces knowledge graph information

### ISSUE THREAD

**Issue by superguopeng** [thunlp/EntityDuetNeuralRanking#19]
I have a question. Knowledge graph information is introduced in the EDRM model architecture, but there is no knowledge graph data in the model training data. Which part of the code introduces the knowledge graph data?

**Comment by EdwardZH** [comment]
The entity embedding can be initialized with the pretrained embeddings (such as TransE). But for Chinese data, we find the relation type is sparse, thus we initialize the entity embedding randomly. On the other hand, in this paper we focus more on semantic information of KG beyond structural information.

**Comment by superguopeng** [comment]
Thank you very much for your reply, but I have another question. You said that the semantic information in the knowledge graph used in the paper is also introduced through pretrained embeddings?

**Comment by EdwardZH** [comment]
We describe our method specifically in our paper.

**Comment by superguopeng** [comment]
Thank you very much for your reply。
