### ISSUE TITLE
Separate matching on title and on Snippet

### ISSUE THREAD

**Issue by pommedeterresautee** [thunlp/EntityDuetNeuralRanking#9]
I have separated the matching Query Vs Title and Query Vs Snippet
It has increased the inference time on 10 cores CPU from 50ms to 67ms (still manageable).
MAP (model with CNN) improved from 0.31 to 0.36 (with raw click on a search engine using BM25).
For what it worths, model without CNN (not separating title and snippet text) had a 0.27 MAP... meaning in my case, separating matching on title and snippet text improves perf in a similar way than adding CNN. 

You may want to test this approach on SOGOU / Bing.

**Comment by EdwardZH** [comment]
I think more information will help to improve model performance. We will test on a public datatset, SogouQCL.

**Comment by EdwardZH** [comment]
Hi, for more neural IR training, data augmentation and more about EDRM. Please refer to our WWW2020 Paper Selective Weak Supervision for Neural Information Retrieval. Thank you for your attention. I will close this issue.
